/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom28.quanlibanhang.ui;

import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

import org.apache.commons.lang3.StringUtils;

import com.nhom28.quanlibanhang.dto.ComboBoxItem;
import com.nhom28.quanlibanhang.pojo.HangHoa;
import com.nhom28.quanlibanhang.pojo.MuaHang;
import com.nhom28.quanlibanhang.pojo.NhanVien;
import com.nhom28.quanlibanhang.service.MuaHangService;
import com.nhom28.quanlibanhang.service.impl.MuaHangServiceImpl;

/**
 * 
 * @author lehuyen
 */
public class BanHangUI extends javax.swing.JFrame {

	private MuaHangService muaHangService = new MuaHangServiceImpl();
	DefaultTableModel model;
	double tongTienThanhToan = 0.0;
	double tongTienHoaDon = 0.0;
	int tongSoLuong = 0;

	/**
	 * Creates new form HoaDon
	 */
	public BanHangUI() {
		try {
			initComponents();
			
			String today = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
			// gan gia tri mac dinh cho ngay tao va ngay thanh toan 
			txt_ngaytao.setText(today);;
			txt_mahoadon.setText(today);
			
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">                          
	private void initComponents() throws Exception {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txt_ngaytao = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		txt_mavach = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txt_soluong = new javax.swing.JTextField();
		btn_ThemHang = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		txt_mahoadon = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel3 = new javax.swing.JPanel();
		btn_LuuPhieu = new javax.swing.JButton();
		btn_XoaDong = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setText("BÁN HÀNG");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("Ngày tạo hóa đơn (dd/mm/yyyy):");

		jPanel1.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("Nhập/Quét mã vạch");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setText("Số lượng");

		btn_ThemHang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btn_ThemHang.setText("Thêm Hàng");
		btn_ThemHang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btn_ThemHangActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel12.setText("Giảm Giá");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(
																txt_mavach,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																150,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(31, 31, 31)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																txt_soluong))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(43,
																				43,
																				43)
																		.addComponent(
																				jTextField2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				233,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				btn_ThemHang))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(122,
																				122,
																				122)
																		.addComponent(
																				jLabel12)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jLabel4)
														.addComponent(jLabel12))
										.addGap(10, 10, 10)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																txt_soluong,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																34,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																35,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																btn_ThemHang,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																43,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txt_mavach,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																33,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(20, 20, 20)));

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel5.setText("Nhân viên bán hàng");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel6.setText("Ngày Thanh Toán (dd/mm/yyyy):");

		jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.RAISED));
		jPanel2.setLayout(new java.awt.GridLayout(1, 0));

		jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		model = new DefaultTableModel();
		String[] columnNames = { "Mã Hàng Hoá", "Tên Hàng Hoá", "Đơn Giá",
				"Số Lượng", "Tổng tiền", "Giảm Tiền Mặt", "Thành Tiền" };
		model.setColumnIdentifiers(columnNames);
		jTable1.setModel(model);
		List<NhanVien> listNhanVien = muaHangService.getAllNhanVien();
		for (NhanVien nhanVien : listNhanVien) {
			jComboBox1.addItem(new ComboBoxItem(nhanVien.getId(), nhanVien
					.getTenNhanVien()));
		}
		jScrollPane1.setViewportView(jTable1);

		jPanel2.add(jScrollPane1);

		jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.RAISED));
		jPanel3.setLayout(new java.awt.GridLayout(5, 1));

		btn_LuuPhieu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btn_LuuPhieu.setText("Lưu Phiếu");
		btn_LuuPhieu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btn_LuuActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jPanel3.add(btn_LuuPhieu);

		btn_XoaDong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btn_XoaDong.setText("Xóa Dòng");
		btn_XoaDong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btn_XoaDongActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jPanel3.add(btn_XoaDong);

		jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.RAISED));

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel7.setText("Tổng tiền hóa đơn ");

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel8.setText("Tổng tiền được giảm ");

		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel9.setText("Tổng tiền cần thanh toán ");

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel10.setText("Số tiền khách hàng trả ");

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel11.setText("Số tiền trả lại khách hàng");

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(255, 0, 0));

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(255, 0, 0));

		jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel15.setForeground(new java.awt.Color(255, 0, 0));

		jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel16.setForeground(new java.awt.Color(255, 0, 0));

		jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jTextField1.getDocument().addDocumentListener(new DocumentListener() {
			public void changedUpdate(DocumentEvent e) {
				warn();
			}

			public void removeUpdate(DocumentEvent e) {
				warn();
			}

			public void insertUpdate(DocumentEvent e) {
				warn();
			}

			public void warn() {
				String tienKhachStr = jTextField1.getText();
				if (!StringUtils.isNumeric(tienKhachStr)) {
					JOptionPane
							.showMessageDialog(
									null,
									"Error: Vui lòng nhập trường Số Tiền Khách Hàng Trả là số",
									"Error Massage", JOptionPane.ERROR_MESSAGE);
				}
				double tienKhach = Double.parseDouble(tienKhachStr);

				double tienTra = tienKhach - tongTienThanhToan;
				String tienTraStr = String.format("%.1f", tienTra);
				jLabel16.setText(tienTraStr);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel4Layout
										.createSequentialGroup()
										.addGap(33, 33, 33)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLabel10,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(jLabel7)
														.addComponent(
																jTextField1)
														.addComponent(
																jLabel13,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel16,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																223,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jLabel11)
																		.addGroup(
																				jPanel4Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel8)
																						.addGap(37,
																								37,
																								37)))
														.addComponent(
																jLabel14,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																223,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(119, 119, 119)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel9)
														.addComponent(
																jLabel15,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																223,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(63, 63, 63)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(jLabel8)
														.addComponent(jLabel9))
										.addGap(9, 9, 9)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel13,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																36,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel14,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																36,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel15,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																36,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel10)
														.addComponent(jLabel11))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLabel16,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																36,
																Short.MAX_VALUE)
														.addComponent(
																jTextField1))
										.addContainerGap(56, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jPanel4,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jPanel2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		1024,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jPanel3,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jPanel1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(18,
																										18,
																										18)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel5)
																												.addComponent(
																														jComboBox1,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														252,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(40,
																										40,
																										40))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										282,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(240,
																										240,
																										240)))
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel2)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																								.addComponent(
																										txt_mahoadon,
																										javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(
																										txt_ngaytao,
																										javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(
																										jLabel6,
																										javax.swing.GroupLayout.Alignment.LEADING)))
																.addGap(18, 18,
																		18)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		39,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		jPanel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel5)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jComboBox1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		28,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(36, 36,
																		36))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel2)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		txt_ngaytao,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jLabel6)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		txt_mahoadon,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(11, 11,
																		11)))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jPanel2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														246, Short.MAX_VALUE)
												.addComponent(
														jPanel3,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		pack();
	}// </editor-fold>

	private void btn_LuuActionPerformed(ActionEvent evt) throws Exception {
		String ngayTao = txt_ngaytao.getText();
		String ngayThanhToan = txt_mahoadon.getText();
		SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		dateFormat.setLenient(false);
		Date ngayTaoDate = dateFormat.parse(ngayTao.trim());
		Date ngayThanhToanDate = dateFormat.parse(ngayThanhToan.trim());
		
		MuaHang muaHang = new MuaHang();
		muaHang.setNgayNhap(ngayTaoDate);
		muaHang.setNgayThanhToan(ngayThanhToanDate);
		muaHang.setTongThanhTien(tongTienHoaDon);
		muaHang.setTongThanhToan(tongTienThanhToan);
		muaHang.setTongSoLuong(tongSoLuong);
		
		muaHangService.saveMuaHang(muaHang);
	}

	private double tinhToan(double giaMua, int soLuong, double giamGia) {
		return (giaMua * soLuong) - giamGia;
	}

	private void loadView() {
		if (jTable1.getRowCount() > 0) {
			double tongTienGiam = 0.0;
			tongTienThanhToan = 0.0;
			tongTienHoaDon = 0;
			tongSoLuong = 0;
			for (int i = 0; i < jTable1.getRowCount(); i++) {
				tongSoLuong += Integer.parseInt(jTable1.getModel()
						.getValueAt(i, 3).toString());
				tongTienHoaDon += Double.parseDouble(jTable1.getModel()
						.getValueAt(i, 4).toString());
				tongTienGiam += Double.parseDouble(jTable1.getModel()
						.getValueAt(i, 5).toString());
				tongTienThanhToan += Double.parseDouble(jTable1.getModel()
						.getValueAt(i, 6).toString());
			}

			String tongTienHoaDonStr = String.format("%.1f", tongTienHoaDon);
			String tongTienGiamStr = String.format("%.1f", tongTienGiam);
			String tongTienThanhToanStr = String.format("%.1f",
					tongTienThanhToan);

			jLabel13.setText(tongTienHoaDonStr);
			jLabel14.setText(tongTienGiamStr);
			jLabel15.setText(tongTienThanhToanStr);
		}
	}

	private void btn_ThemHangActionPerformed(java.awt.event.ActionEvent evt)
			throws SQLException {
		String maVach = txt_mavach.getText();
		String soLuongStr = txt_soluong.getText();
		String giamGiaStr = jTextField2.getText();
		if (!StringUtils.isNumeric(soLuongStr)) {
			JOptionPane.showMessageDialog(null,
					"Error: Vui lòng nhập số lượng là số", "Error Massage",
					JOptionPane.ERROR_MESSAGE);
		}

		if (!StringUtils.isNumeric(giamGiaStr)) {
			JOptionPane.showMessageDialog(null,
					"Error: Vui lòng nhập trường Giảm Giá là số",
					"Error Massage", JOptionPane.ERROR_MESSAGE);
		}

		int soLuong = Integer.parseInt(txt_soluong.getText());
		double giamGia = Double.parseDouble(jTextField2.getText());

		HangHoa hh = muaHangService.getHangHoaByMaVach(maVach);
		String maHangHoa = hh.getMaHangHoa();
		String tenHangHoa = hh.getTenHangHoa();
		Double giaMua = hh.getGiaMua();
		Double tongTien = tinhToan(giaMua, soLuong, 0);
		Double thanhTien = tinhToan(giaMua, soLuong, giamGia);

		String giaMuaStr = String.format("%.1f", giaMua);
		String thanhTienStr = String.format("%.1f", thanhTien);
		giamGiaStr = String.format("%.1f", giamGia);
		model.addRow(new Object[] { maHangHoa, tenHangHoa, giaMuaStr, soLuong,
				tongTien, giamGiaStr, thanhTienStr });

		loadView();
	}

	private void btn_XoaDongActionPerformed(java.awt.event.ActionEvent evt) {
		int row = 0;
		if ((row = jTable1.getSelectedRow()) >= 0) {
			model = (DefaultTableModel) jTable1.getModel();
			model.removeRow(row);
			loadView();
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BanHangUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BanHangUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BanHangUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BanHangUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BanHangUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btn_LuuPhieu;
	private javax.swing.JButton btn_ThemHang;
	private javax.swing.JButton btn_XoaDong;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField txt_mahoadon;
	private javax.swing.JTextField txt_mavach;
	private javax.swing.JTextField txt_ngaytao;
	private javax.swing.JTextField txt_soluong;
	// End of variables declaration
}
