/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom28.quanlibanhang.ui;

import java.sql.SQLException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import com.nhom28.quanlibanhang.common.DialogMessages;
import com.nhom28.quanlibanhang.common.GlobalVariables;
import com.nhom28.quanlibanhang.dto.ComboItem;
import com.nhom28.quanlibanhang.pojo.HangHoa;
import com.nhom28.quanlibanhang.pojo.KhachHang;
import com.nhom28.quanlibanhang.pojo.KhuVuc;
import com.nhom28.quanlibanhang.service.HangHoaService;
import com.nhom28.quanlibanhang.service.impl.HangHoaServiceImpl;

/**
 *
 * @author Google
 */
public class HangHoaJFrame extends javax.swing.JFrame {
	
	HangHoaService hangHoaService = new HangHoaServiceImpl();
	
	int selectItem = 0;

    /**
     * Creates new form HangHoaJFrame
     */
    public HangHoaJFrame() {
        initComponents();
        loadRecords();
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent evt) {
				if (jTable1.getSelectedRow() >= 0) {
                	int selectedRow = jTable1.getSelectedRow();
                	selectItem = Integer.parseInt(jTable1.getModel().getValueAt(selectedRow, 0).toString());
                    
                }
			}
		});
    }
    
	private void loadRecords() {

		List<HangHoa> hangHoaList = hangHoaService.getAllHangHoa();
		String titleColumns[] = { "ID", "Nhóm Hàng", "Mã Hàng Hóa",
				"Mã Vạch", "Tên Hàng Hóa", "Đơn Vị Tính", "Xuất Xứ",
				"Thuế", "Tồn Kho Tối Thiểu", "Tồn Kho Hiện Tại",
				"Nhà Phân Phối", "Giá Mua", "Giá Bán Sỉ", "Giá Bán Lẻ"};
		TableModel tableModel = new DefaultTableModel(titleColumns, 0) {
			@Override
			public boolean isCellEditable(int row, int column) {
				return true;
			}
		};

		jTable1.setModel(tableModel);
		for (int i = 0; i < hangHoaList.size(); i++) {
			HangHoa hh = hangHoaList.get(i);
			int ma = hh.getId();
			String nhomHang = hh.getNhomHang().getTenNhomHang();
			String maHangHoa = hh.getMaHangHoa();
			String maVach = hh.getMaVachNhaSanXuat();
			String tenHangHoa = hh.getTenHangHoa();
			String donViTinh = hh.getDonViTinh().getTenDonViTinh();
			String xuatXuat = hh.getXuatXu();

			String thue = hh.getThue();
			long tonKhoToiThieu = hh.getTonKhoToiThieu();
			long tonKhoHienTai = hh.getTonKhoHienTai();
			String nhaPhanPhoi = hh.getNhaPhanPhoi().getTenNhaPhanPhoi();
			double giaMua = hh.getGiaMua();
			double giaBanSi = hh.getGiaBanSi();
			double giaBanLe = hh.getGiaBanLe();
			
			Object[] data = { ma, nhomHang, maHangHoa, maVach, tenHangHoa, donViTinh, xuatXuat,
					thue, tonKhoToiThieu, tonKhoHienTai, nhaPhanPhoi,
					giaMua, giaBanSi, giaBanLe};
			((DefaultTableModel) tableModel).addRow(data);
		}

	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnXemChiTiet = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh Sách Hàng Hóa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnXemChiTiet.setText("Xem Chi Tiết");
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        btnThemMoi.setText("Thêm Mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Sửa");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa Hàng Hóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnXemChiTiet)
                .addGap(36, 36, 36)
                .addComponent(btnThemMoi)
                .addGap(37, 37, 37)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnXoa)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemChiTiet)
                    .addComponent(btnThemMoi)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
    	GlobalVariables.TEMP = String.valueOf(selectItem);
    	CapNhatHangHoaFrame.trangThai = 0;
    	
    	CapNhatHangHoaFrame capNhatHangHang = new CapNhatHangHoaFrame();        
        capNhatHangHang.setVisible(true);
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
    	CapNhatHangHoaFrame.trangThai = 1;
    	CapNhatHangHoaFrame capNhat = new CapNhatHangHoaFrame();
        
        capNhat.setVisible(true);
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    	int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có muốn Xoá không?", "Xác Nhận?", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            
                try {
                	HangHoa hh = hangHoaService.findHangHoaByMa(selectItem);
            		hangHoaService.delete(hh);
                } catch (Exception ex) {
                	DialogMessages.errorBox("Không Thể Xóa Dữ Liệu Này - Khóa Ngoại", "Không Xóa Được");
                }
        		
        		
                loadRecords();
            
            
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangHoaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangHoaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangHoaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangHoaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangHoaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
