package com.nhom28.quanlibanhang.ui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import com.nhom28.quanlibanhang.dto.ComboItem;
import com.nhom28.quanlibanhang.pojo.KhuVuc;
import com.nhom28.quanlibanhang.pojo.NhaPhanPhoi;
import com.nhom28.quanlibanhang.service.NhanPhanPhoiService;
import com.nhom28.quanlibanhang.service.impl.NhaPhanPhoiServiceImpl;

/**
 *
 * @author Google
 */
public class NhaPhanPhoiFrame extends javax.swing.JFrame {
	
	NhanPhanPhoiService nhaPhanPhoi = new NhaPhanPhoiServiceImpl();
	
	 List<KhuVuc> khuVucList = nhaPhanPhoi.getListKhuVuc();

    /**
     * Creates new form NhaPhanPhoiFrame
     */
    public NhaPhanPhoiFrame() {
        initComponents();
        myInitComponents();
            try {
                loadRecords();
            } catch (SQLException ex) {
                Logger.getLogger(NhaPhanPhoiFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        txtId.setEnabled(false);
        if(jTable1.getRowCount() > 0) {
        	jTable1.changeSelection(0, 0, false, false);
        }
    }
    
    public void myInitComponents() {
    	
    	List<ComboItem> items = new ArrayList<>();
    	List<KhuVuc> khuVucList = nhaPhanPhoi.getListKhuVuc();
    	for (KhuVuc khuVuc : khuVucList) {
    		jComboBox1.addItem(new ComboItem(String.valueOf(khuVuc.getId()), khuVuc.getTenKhuVuc()));
		}
    	
    	
    }
    
    private void loadRecords() throws SQLException {
		List<NhaPhanPhoi> nppList = nhaPhanPhoi.getAllNhaPhanPhoi();
        String titleColumn[] = {"ID", "Mã Nhà Phân Phối", "Khu Vực"
                , "Tên Nhà Phân Phối", "Địa Chỉ", "Mã Số Thuế",
                "Điện Thoại", "Di Động", "Email", "Website", "Số Tài Khoàn",
                "Ngân Hàng", "Fax"};
            TableModel tableModel = new DefaultTableModel(titleColumn, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return true;
                }
            };

        jTable1.setModel(tableModel);     
        for (int i = 0; i < nppList.size(); i++) {
        	NhaPhanPhoi npp = nppList.get(i);
            int id = npp.getId();
            String maNhaPhanPhoi = npp.getMaNhaPhanPhoi();
           
            int idkhuVuc = npp.getKhuVuc().getId();
            String tenKhuVuc = "";
            for (KhuVuc khuVuc : khuVucList) {
				if(khuVuc.getId() == idkhuVuc) {
					tenKhuVuc = khuVuc.getTenKhuVuc();					
				}
			}
           
            
            String TenNhaPhanPhoi = npp.getTenNhaPhanPhoi();
            String diaChi = npp.getDiaChi();
            String maSoThue = npp.getMaSoThue();
            String dienThoai = npp.getDienThoai();
            String diDong = npp.getDiDong();
            String email = npp.getEmail();
            String website = npp.getWebsite();
            String soTaiKhoan = npp.getSoTaiKhoan();
            String nganHang = npp.getNganHang();
            String fax = npp.getFax();
            

            Object[] data = { id, maNhaPhanPhoi, tenKhuVuc, TenNhaPhanPhoi,
            		diaChi, maSoThue, dienThoai, diDong, email, website, soTaiKhoan, nganHang,
            		fax};
            ((DefaultTableModel) tableModel).addRow(data);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaNhaPhanPhoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenNhaPhanPhoi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaSoThue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDiDong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtWebsite = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSoTaiKhoan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNganHang = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<ComboItem>();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhà Phân Phối");

        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent evt) {
				if (jTable1.getSelectedRow() >= 0) {
                	int selectedRow = jTable1.getSelectedRow();
                    
                    int id = Integer.parseInt(jTable1.getModel().getValueAt(selectedRow, 0).toString());
                    String maNhaPhanPhoi = jTable1.getModel().getValueAt(selectedRow, 1).toString();
                    String khuVuc = jTable1.getModel().getValueAt(selectedRow, 2).toString();
                    String TenNhaPhanPhoi = jTable1.getModel().getValueAt(selectedRow, 3).toString();
                    String diaChi = jTable1.getModel().getValueAt(selectedRow, 4).toString();
                    String maSoThue = jTable1.getModel().getValueAt(selectedRow, 5).toString();
                    String dienThoai = jTable1.getModel().getValueAt(selectedRow, 6).toString();
                    String diDong = jTable1.getModel().getValueAt(selectedRow, 7).toString();
                    String email = jTable1.getModel().getValueAt(selectedRow, 8).toString();
                    String website = jTable1.getModel().getValueAt(selectedRow, 9).toString();
                    String soTaiKhoan = jTable1.getModel().getValueAt(selectedRow, 10).toString();
                    String nganHang = jTable1.getModel().getValueAt(selectedRow, 11).toString();
                    String fax = jTable1.getModel().getValueAt(selectedRow, 12).toString();
                    
                    txtId.setText(id+"");                    
                    txtMaNhaPhanPhoi.setText(maNhaPhanPhoi);                   
                    txtTenNhaPhanPhoi.setText(TenNhaPhanPhoi);
                    
                    int key = 0;
                    for (KhuVuc kv : khuVucList) {
                    	if(khuVuc.equalsIgnoreCase(kv.getTenKhuVuc())) {
                    		key = kv.getId();
                    	}
					}
                    ComboItem item = new ComboItem(String.valueOf(key), khuVuc);
                    
                    jComboBox1.setSelectedItem(item);
                    txtDiachi.setText(diaChi);
                    txtMaSoThue.setText(maSoThue);
                    txtDienThoai.setText(dienThoai);
                    txtDiDong.setText(diDong);
                    txtEmail.setText(email);
                    txtWebsite.setText(website);
                    txtSoTaiKhoan.setText(soTaiKhoan);
                    txtNganHang.setText(nganHang);
                    txtFax.setText(fax);
                   
                }
			}
		});
        
       
        
       
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhà Phân Phối", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel1.setText("ID:");

        jLabel2.setText("Mã Nhà Phân Phối:");

        jLabel3.setText("Khu Vực:");

        jLabel4.setText("Tên nhà phân phối:");

        jLabel5.setText("Mã số thuế:");

        jLabel6.setText("Địa chỉ:");

        jLabel7.setText("Fax:");

        jLabel8.setText("Điện thoại:");

        jLabel9.setText("Di động:");

        jLabel10.setText("Email:");

        jLabel11.setText("Website:");

        jLabel12.setText("Số tài khoản:");

        jLabel13.setText("Ngân hàng");

        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaNhaPhanPhoi, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenNhaPhanPhoi)
                                .addComponent(txtDiachi)
                                .addComponent(txtMaSoThue)
                                .addComponent(txtDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiDong, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFax, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNganHang, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDiDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNhaPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenNhaPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jLabel13)
                    .addComponent(txtNganHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnThem)
                .addGap(39, 39, 39)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnSua)
                .addGap(74, 74, 74)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnThoat)
                    .addComponent(btnThem)
                    .addComponent(btnSua)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    	int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa nhà phân phối này không?", "Xác Nhận Xóa?", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                //deleteRecord();
            	
            	Integer id = Integer.parseInt(txtId.getText());
            
            	NhaPhanPhoi entity = nhaPhanPhoi.findNhaPhanPhoiById(id);
            	
            	nhaPhanPhoi.delete(entity);;

                loadRecords();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    	int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa thông tin nhà phân phối không?", "Xác Nhận?", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            
        	try {
        		// lay thong tin nha phan phoi        		
                NhaPhanPhoi npp = new NhaPhanPhoi();
                npp.setId(Integer.parseInt(txtId.getText()));
                npp.setMaNhaPhanPhoi(txtMaNhaPhanPhoi.getText());
                
                Object item = jComboBox1.getSelectedItem();
                String key = ((ComboItem)item).getKey();                
                KhuVuc kv = new KhuVuc();
                
                               
                for (KhuVuc kc : khuVucList) {
					if(key.equalsIgnoreCase(String.valueOf(kc.getId()))) {
						kv = kc;
						break;
					}
				}
                
                npp.setKhuVuc(kv);
                npp.setTenNhaPhanPhoi(txtTenNhaPhanPhoi.getText());
                npp.setDiaChi(txtDiachi.getText());
                npp.setMaSoThue(txtMaSoThue.getText());
                npp.setDienThoai(txtDienThoai.getText());
                npp.setDiDong(txtDiDong.getText());
                npp.setEmail(txtEmail.getText());
                npp.setWebsite(txtWebsite.getText());
                npp.setSoTaiKhoan(txtSoTaiKhoan.getText());
                npp.setNganHang(txtNganHang.getText());
                npp.setFax(txtFax.getText());
                
                nhaPhanPhoi.update(npp);

                loadRecords();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
            
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    	int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thêm nhà phân phối không?", "Xác Nhận?", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            
        	try {
        		// lay thong tin nha phan phoi        		
                NhaPhanPhoi npp = new NhaPhanPhoi();
                npp.setMaNhaPhanPhoi(txtMaNhaPhanPhoi.getText());
                
                Object item = jComboBox1.getSelectedItem();
                String key = ((ComboItem)item).getKey();                
                KhuVuc kv = new KhuVuc();
                
                               
                for (KhuVuc kc : khuVucList) {
					if(key.equalsIgnoreCase(String.valueOf(kc.getId()))) {
						kv = kc;
						break;
					}
				}
                npp.setKhuVuc(kv);
                npp.setTenNhaPhanPhoi(txtTenNhaPhanPhoi.getText());
                npp.setDiaChi(txtDiachi.getText());
                npp.setMaSoThue(txtMaSoThue.getText());
                npp.setDienThoai(txtDienThoai.getText());
                npp.setDiDong(txtDiDong.getText());
                npp.setEmail(txtEmail.getText());
                npp.setWebsite(txtWebsite.getText());
                npp.setSoTaiKhoan(txtSoTaiKhoan.getText());
                npp.setNganHang(txtNganHang.getText());
                npp.setFax(txtFax.getText());
                
                nhaPhanPhoi.insert(npp);

                loadRecords();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhaPhanPhoiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhaPhanPhoiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhaPhanPhoiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhaPhanPhoiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhaPhanPhoiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private JComboBox<ComboItem> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDiDong;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMaNhaPhanPhoi;
    private javax.swing.JTextField txtMaSoThue;
    private javax.swing.JTextField txtNganHang;
    private javax.swing.JTextField txtSoTaiKhoan;
    private javax.swing.JTextField txtTenNhaPhanPhoi;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables
}
