package com.nhom28.quanlibanhang.ui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import org.apache.commons.lang3.math.IEEE754rUtils;

import com.nhom28.quanlibanhang.dto.ComboItem;
import com.nhom28.quanlibanhang.pojo.KhuVuc;
import com.nhom28.quanlibanhang.pojo.NguoiDung;
import com.nhom28.quanlibanhang.pojo.NhaPhanPhoi;
import com.nhom28.quanlibanhang.pojo.NhatKyHeThong;
import com.nhom28.quanlibanhang.service.NguoiDungService;
import com.nhom28.quanlibanhang.service.NhanPhanPhoiService;
import com.nhom28.quanlibanhang.service.NhatKyHeThongService;
import com.nhom28.quanlibanhang.service.impl.NguoiDungServiceImpl;
import com.nhom28.quanlibanhang.service.impl.NhatKyHeThongServiceImpl;

/**
 *
 * @author Google
 */
public class NhatKyHeThongUI extends javax.swing.JFrame {
	
	NhatKyHeThongService nkService = new NhatKyHeThongServiceImpl();

    /**
     * Creates new form NhatKyHeThongUI
     */
    public NhatKyHeThongUI() {
        initComponents();
        myInitComponents();
        
		loadRecords();
		
    }
    
    NguoiDungService nguoiDungService = new NguoiDungServiceImpl();    	
	List<NguoiDung> nguoiDungList = nguoiDungService.getAllNguoiDung();
    public void myInitComponents() {
    	
    	for (NguoiDung nguoi : nguoiDungList) {
    		cbbNguoiDung.addItem(new ComboItem(String.valueOf(nguoi.getId()), nguoi.getTenDangNhap()));
		}
    	
    	
    }
    
    private void loadRecords() {
		List<NhatKyHeThong> nppList = nkService.getTatCaNhatKy();
        String titleColumn[] = {"Số Thứ Tự", "Người Dùng", "Thao Tác"
                , "Chi Tiết", "Ghi Chú", "Ngày"};
            TableModel tableModel = new DefaultTableModel(titleColumn, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return true;
                }
            };

        jTable1.setModel(tableModel);     
        for (int i = 0; i < nppList.size(); i++) {
        	NhatKyHeThong nk = nppList.get(i);
            int id = nk.getId();
            String nguoidung = String.valueOf(nk.getIdNguoiDung());
           
            String thaotac = nk.getThaoTac();
            String chiTiet = nk.getChiTiet();
            String ghiChu = nk.getGhiChu();
            Date ngay = nk.getNgay();
            
            

            Object[] data = { id, nguoidung, thaotac, chiTiet,
            		ghiChu, ngay};
            ((DefaultTableModel) tableModel).addRow(data);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtThaoTac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taChiTiet = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        cbbNguoiDung = new javax.swing.JComboBox<ComboItem>();
        btnXoa1Dong = new javax.swing.JButton();
        btnXoaAll = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhật Ký Hệ Thống");

        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent evt) {
				if (jTable1.getSelectedRow() >= 0) {
                	int selectedRow = jTable1.getSelectedRow();
                    
                    int id = Integer.parseInt(jTable1.getModel().getValueAt(selectedRow, 0).toString());
                    String nguoidung = jTable1.getModel().getValueAt(selectedRow, 1).toString();
                    String thaotac = jTable1.getModel().getValueAt(selectedRow, 2).toString();
                    String chiTiet = jTable1.getModel().getValueAt(selectedRow, 3).toString();
                    String ghiChu = jTable1.getModel().getValueAt(selectedRow, 4).toString();
                    String ngay = jTable1.getModel().getValueAt(selectedRow, 5).toString();
                   
                    
                    txtStt.setText(id+"");  
                    
                    String account = "";
                    for (NguoiDung nguoiDung : nguoiDungList) {
                    	if(nguoidung.equalsIgnoreCase(String.valueOf(nguoiDung.getId()))) {
                    		account = nguoiDung.getTenDangNhap();
                    	}
					}
                    ComboItem item = new ComboItem(nguoidung, account);
                    
                    cbbNguoiDung.setSelectedItem(item);
                    
                    
                    
                    txtThaoTac.setText(thaotac);                   
                    taChiTiet.setText(chiTiet);
                    txtGhiChu.setText(ghiChu);
                    txtNgay.setText(ngay);
                   
                }
			}
		});
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhật Ký Hệ Thống", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel1.setText("Số Thứ Tự:");

        jLabel2.setText("Người Dùng:");

        jLabel3.setText("Thao Tác:");

        jLabel4.setText("Ngày");

        jLabel5.setText("Chi Tiết:");

        taChiTiet.setColumns(20);
        taChiTiet.setRows(5);
        jScrollPane2.setViewportView(taChiTiet);

        jLabel6.setText("Ghi Chú:");

        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStt)
                            .addComponent(txtThaoTac)
                            .addComponent(txtNgay)
                            .addComponent(cbbNguoiDung, 0, 180, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtGhiChu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtStt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbbNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnXoa1Dong.setText("Xóa 1 Dòng");
        btnXoa1Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1DongActionPerformed(evt);
            }
        });

        btnXoaAll.setText("Xóa Tất Cả");
        btnXoaAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaAllActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnXoa1Dong)
                        .addGap(53, 53, 53)
                        .addComponent(btnXoaAll)
                        .addGap(63, 63, 63)
                        .addComponent(btnThoat)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa1Dong)
                    .addComponent(btnXoaAll)
                    .addComponent(btnThoat))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoa1DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1DongActionPerformed
        // TODO add your handling code here:
    	int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa Dòng Nhật Ký này không?", "Xác Nhận Xóa?", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            
                //deleteRecord();
            	
            	Integer id = Integer.parseInt(txtStt.getText());
            
            	NhatKyHeThong nk = nkService.findNhatKyByMa(id);
            	
            	nkService.deleteNhatKy(nk);

                loadRecords();
           
        }
    }//GEN-LAST:event_btnXoa1DongActionPerformed

    private void btnXoaAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaAllActionPerformed
        // TODO add your handling code here:
    	int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa Tất Cả Nhật Ký này không?", "Cảnh Báo", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            	nkService.deleteAllNhatKy();

                loadRecords();
           
        }
    }//GEN-LAST:event_btnXoaAllActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhatKyHeThongUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhatKyHeThongUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhatKyHeThongUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhatKyHeThongUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhatKyHeThongUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa1Dong;
    private javax.swing.JButton btnXoaAll;
    private JComboBox<ComboItem> cbbNguoiDung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea taChiTiet;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtStt;
    private javax.swing.JTextField txtThaoTac;
    // End of variables declaration//GEN-END:variables
}
