package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BoPhan generated by hbm2java
 */
public class BoPhan implements java.io.Serializable {

	private Integer id;
	private String tenBoPhan;
	private int idNguoiQuanLy;
	private String ghiChu;
	private byte conQuanLy;
	private Set<NhanVien> nhanViens = new HashSet<NhanVien>(0);

	public BoPhan() {
	}

	public BoPhan(String tenBoPhan, int idNguoiQuanLy, byte conQuanLy) {
		this.tenBoPhan = tenBoPhan;
		this.idNguoiQuanLy = idNguoiQuanLy;
		this.conQuanLy = conQuanLy;
	}

	public BoPhan(String tenBoPhan, int idNguoiQuanLy, String ghiChu,
			byte conQuanLy, Set<NhanVien> nhanViens) {
		this.tenBoPhan = tenBoPhan;
		this.idNguoiQuanLy = idNguoiQuanLy;
		this.ghiChu = ghiChu;
		this.conQuanLy = conQuanLy;
		this.nhanViens = nhanViens;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTenBoPhan() {
		return this.tenBoPhan;
	}

	public void setTenBoPhan(String tenBoPhan) {
		this.tenBoPhan = tenBoPhan;
	}

	public int getIdNguoiQuanLy() {
		return this.idNguoiQuanLy;
	}

	public void setIdNguoiQuanLy(int idNguoiQuanLy) {
		this.idNguoiQuanLy = idNguoiQuanLy;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public byte getConQuanLy() {
		return this.conQuanLy;
	}

	public void setConQuanLy(byte conQuanLy) {
		this.conQuanLy = conQuanLy;
	}

	public Set<NhanVien> getNhanViens() {
		return this.nhanViens;
	}

	public void setNhanViens(Set<NhanVien> nhanViens) {
		this.nhanViens = nhanViens;
	}

}
