package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

/**
 * ChiTietBanHang generated by hbm2java
 */
public class ChiTietBanHang implements java.io.Serializable {

	private Integer id;
	private HangHoa hangHoa;
	private BanHang banHang;
	private Kho kho;
	private float giaBan;
	private int soLuong;
	private double thanhTien;
	private int vat;
	private String ghiChu;

	public ChiTietBanHang() {
	}

	public ChiTietBanHang(HangHoa hangHoa, BanHang banHang, Kho kho,
			float giaBan, int soLuong, double thanhTien, int vat) {
		this.hangHoa = hangHoa;
		this.banHang = banHang;
		this.kho = kho;
		this.giaBan = giaBan;
		this.soLuong = soLuong;
		this.thanhTien = thanhTien;
		this.vat = vat;
	}

	public ChiTietBanHang(HangHoa hangHoa, BanHang banHang, Kho kho,
			float giaBan, int soLuong, double thanhTien, int vat, String ghiChu) {
		this.hangHoa = hangHoa;
		this.banHang = banHang;
		this.kho = kho;
		this.giaBan = giaBan;
		this.soLuong = soLuong;
		this.thanhTien = thanhTien;
		this.vat = vat;
		this.ghiChu = ghiChu;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public HangHoa getHangHoa() {
		return this.hangHoa;
	}

	public void setHangHoa(HangHoa hangHoa) {
		this.hangHoa = hangHoa;
	}

	public BanHang getBanHang() {
		return this.banHang;
	}

	public void setBanHang(BanHang banHang) {
		this.banHang = banHang;
	}

	public Kho getKho() {
		return this.kho;
	}

	public void setKho(Kho kho) {
		this.kho = kho;
	}

	public float getGiaBan() {
		return this.giaBan;
	}

	public void setGiaBan(float giaBan) {
		this.giaBan = giaBan;
	}

	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	public double getThanhTien() {
		return this.thanhTien;
	}

	public void setThanhTien(double thanhTien) {
		this.thanhTien = thanhTien;
	}

	public int getVat() {
		return this.vat;
	}

	public void setVat(int vat) {
		this.vat = vat;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

}
