package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

/**
 * ChiTietChuyenKho generated by hbm2java
 */
public class ChiTietChuyenKho implements java.io.Serializable {

	private Integer id;
	private ChuyenKho chuyenKho;
	private HangHoa hangHoa;
	private long soLuong;

	public ChiTietChuyenKho() {
	}

	public ChiTietChuyenKho(ChuyenKho chuyenKho, HangHoa hangHoa, long soLuong) {
		this.chuyenKho = chuyenKho;
		this.hangHoa = hangHoa;
		this.soLuong = soLuong;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ChuyenKho getChuyenKho() {
		return this.chuyenKho;
	}

	public void setChuyenKho(ChuyenKho chuyenKho) {
		this.chuyenKho = chuyenKho;
	}

	public HangHoa getHangHoa() {
		return this.hangHoa;
	}

	public void setHangHoa(HangHoa hangHoa) {
		this.hangHoa = hangHoa;
	}

	public long getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(long soLuong) {
		this.soLuong = soLuong;
	}

}
