package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * HangHoa generated by hbm2java
 */
public class HangHoa implements java.io.Serializable {

	private Integer id;
	private DonViTinh donViTinh;
	private NhaPhanPhoi nhaPhanPhoi;
	private NhomHang nhomHang;
	private String maHangHoa;
	private String maVachNhaSanXuat;
	private String tenHangHoa;
	private String xuatXu;
	private String thue;
	private long tonKhoToiThieu;
	private long tonKhoHienTai;
	private String hinhAnh;
	private byte laDichVu;
	private double giaMua;
	private double giaBanSi;
	private double giaBanLe;
	private Set<ChiTietMuaHang> chiTietMuaHangs = new HashSet<ChiTietMuaHang>(0);
	private Set<ChiTietChuyenKho> chiTietChuyenKhos = new HashSet<ChiTietChuyenKho>(
			0);
	private Set<SoDuDauKy> soDuDauKies = new HashSet<SoDuDauKy>(0);
	private Set<ChiTietBanHang> chiTietBanHangs = new HashSet<ChiTietBanHang>(0);

	public HangHoa() {
	}

	public HangHoa(DonViTinh donViTinh, NhaPhanPhoi nhaPhanPhoi,
			NhomHang nhomHang, String maHangHoa, String tenHangHoa,
			long tonKhoToiThieu, long tonKhoHienTai, byte laDichVu,
			double giaMua, double giaBanSi, double giaBanLe) {
		this.donViTinh = donViTinh;
		this.nhaPhanPhoi = nhaPhanPhoi;
		this.nhomHang = nhomHang;
		this.maHangHoa = maHangHoa;
		this.tenHangHoa = tenHangHoa;
		this.tonKhoToiThieu = tonKhoToiThieu;
		this.tonKhoHienTai = tonKhoHienTai;
		this.laDichVu = laDichVu;
		this.giaMua = giaMua;
		this.giaBanSi = giaBanSi;
		this.giaBanLe = giaBanLe;
	}

	public HangHoa(DonViTinh donViTinh, NhaPhanPhoi nhaPhanPhoi,
			NhomHang nhomHang, String maHangHoa, String maVachNhaSanXuat,
			String tenHangHoa, String xuatXu, String thue, long tonKhoToiThieu,
			long tonKhoHienTai, String hinhAnh, byte laDichVu, double giaMua,
			double giaBanSi, double giaBanLe,
			Set<ChiTietMuaHang> chiTietMuaHangs,
			Set<ChiTietChuyenKho> chiTietChuyenKhos,
			Set<SoDuDauKy> soDuDauKies, Set<ChiTietBanHang> chiTietBanHangs) {
		this.donViTinh = donViTinh;
		this.nhaPhanPhoi = nhaPhanPhoi;
		this.nhomHang = nhomHang;
		this.maHangHoa = maHangHoa;
		this.maVachNhaSanXuat = maVachNhaSanXuat;
		this.tenHangHoa = tenHangHoa;
		this.xuatXu = xuatXu;
		this.thue = thue;
		this.tonKhoToiThieu = tonKhoToiThieu;
		this.tonKhoHienTai = tonKhoHienTai;
		this.hinhAnh = hinhAnh;
		this.laDichVu = laDichVu;
		this.giaMua = giaMua;
		this.giaBanSi = giaBanSi;
		this.giaBanLe = giaBanLe;
		this.chiTietMuaHangs = chiTietMuaHangs;
		this.chiTietChuyenKhos = chiTietChuyenKhos;
		this.soDuDauKies = soDuDauKies;
		this.chiTietBanHangs = chiTietBanHangs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public DonViTinh getDonViTinh() {
		return this.donViTinh;
	}

	public void setDonViTinh(DonViTinh donViTinh) {
		this.donViTinh = donViTinh;
	}

	public NhaPhanPhoi getNhaPhanPhoi() {
		return this.nhaPhanPhoi;
	}

	public void setNhaPhanPhoi(NhaPhanPhoi nhaPhanPhoi) {
		this.nhaPhanPhoi = nhaPhanPhoi;
	}

	public NhomHang getNhomHang() {
		return this.nhomHang;
	}

	public void setNhomHang(NhomHang nhomHang) {
		this.nhomHang = nhomHang;
	}

	public String getMaHangHoa() {
		return this.maHangHoa;
	}

	public void setMaHangHoa(String maHangHoa) {
		this.maHangHoa = maHangHoa;
	}

	public String getMaVachNhaSanXuat() {
		return this.maVachNhaSanXuat;
	}

	public void setMaVachNhaSanXuat(String maVachNhaSanXuat) {
		this.maVachNhaSanXuat = maVachNhaSanXuat;
	}

	public String getTenHangHoa() {
		return this.tenHangHoa;
	}

	public void setTenHangHoa(String tenHangHoa) {
		this.tenHangHoa = tenHangHoa;
	}

	public String getXuatXu() {
		return this.xuatXu;
	}

	public void setXuatXu(String xuatXu) {
		this.xuatXu = xuatXu;
	}

	public String getThue() {
		return this.thue;
	}

	public void setThue(String thue) {
		this.thue = thue;
	}

	public long getTonKhoToiThieu() {
		return this.tonKhoToiThieu;
	}

	public void setTonKhoToiThieu(long tonKhoToiThieu) {
		this.tonKhoToiThieu = tonKhoToiThieu;
	}

	public long getTonKhoHienTai() {
		return this.tonKhoHienTai;
	}

	public void setTonKhoHienTai(long tonKhoHienTai) {
		this.tonKhoHienTai = tonKhoHienTai;
	}

	public String getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	public byte getLaDichVu() {
		return this.laDichVu;
	}

	public void setLaDichVu(byte laDichVu) {
		this.laDichVu = laDichVu;
	}

	public double getGiaMua() {
		return this.giaMua;
	}

	public void setGiaMua(double giaMua) {
		this.giaMua = giaMua;
	}

	public double getGiaBanSi() {
		return this.giaBanSi;
	}

	public void setGiaBanSi(double giaBanSi) {
		this.giaBanSi = giaBanSi;
	}

	public double getGiaBanLe() {
		return this.giaBanLe;
	}

	public void setGiaBanLe(double giaBanLe) {
		this.giaBanLe = giaBanLe;
	}

	public Set<ChiTietMuaHang> getChiTietMuaHangs() {
		return this.chiTietMuaHangs;
	}

	public void setChiTietMuaHangs(Set<ChiTietMuaHang> chiTietMuaHangs) {
		this.chiTietMuaHangs = chiTietMuaHangs;
	}

	public Set<ChiTietChuyenKho> getChiTietChuyenKhos() {
		return this.chiTietChuyenKhos;
	}

	public void setChiTietChuyenKhos(Set<ChiTietChuyenKho> chiTietChuyenKhos) {
		this.chiTietChuyenKhos = chiTietChuyenKhos;
	}

	public Set<SoDuDauKy> getSoDuDauKies() {
		return this.soDuDauKies;
	}

	public void setSoDuDauKies(Set<SoDuDauKy> soDuDauKies) {
		this.soDuDauKies = soDuDauKies;
	}

	public Set<ChiTietBanHang> getChiTietBanHangs() {
		return this.chiTietBanHangs;
	}

	public void setChiTietBanHangs(Set<ChiTietBanHang> chiTietBanHangs) {
		this.chiTietBanHangs = chiTietBanHangs;
	}

}
