package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 17, 2016 12:29:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HoaDon generated by hbm2java
 */
public class HoaDon implements java.io.Serializable {

	private Integer id;
	private KhachHang khachHang;
	private HangHoa hangHoa;
	private int giaBan;
	private int khuyenMai;
	private int soLuong;
	private int thanhTien;
	private String thongTinGiaoHang;
	private Date ngayLapHoaDon;
	private Set<LichSuBanHang> lichSuBanHangs = new HashSet<LichSuBanHang>(0);

	public HoaDon() {
	}

	public HoaDon(KhachHang khachHang, HangHoa hangHoa, int giaBan,
			int khuyenMai, int soLuong, int thanhTien, String thongTinGiaoHang,
			Date ngayLapHoaDon) {
		this.khachHang = khachHang;
		this.hangHoa = hangHoa;
		this.giaBan = giaBan;
		this.khuyenMai = khuyenMai;
		this.soLuong = soLuong;
		this.thanhTien = thanhTien;
		this.thongTinGiaoHang = thongTinGiaoHang;
		this.ngayLapHoaDon = ngayLapHoaDon;
	}

	public HoaDon(KhachHang khachHang, HangHoa hangHoa, int giaBan,
			int khuyenMai, int soLuong, int thanhTien, String thongTinGiaoHang,
			Date ngayLapHoaDon, Set<LichSuBanHang> lichSuBanHangs) {
		this.khachHang = khachHang;
		this.hangHoa = hangHoa;
		this.giaBan = giaBan;
		this.khuyenMai = khuyenMai;
		this.soLuong = soLuong;
		this.thanhTien = thanhTien;
		this.thongTinGiaoHang = thongTinGiaoHang;
		this.ngayLapHoaDon = ngayLapHoaDon;
		this.lichSuBanHangs = lichSuBanHangs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	public HangHoa getHangHoa() {
		return this.hangHoa;
	}

	public void setHangHoa(HangHoa hangHoa) {
		this.hangHoa = hangHoa;
	}

	public int getGiaBan() {
		return this.giaBan;
	}

	public void setGiaBan(int giaBan) {
		this.giaBan = giaBan;
	}

	public int getKhuyenMai() {
		return this.khuyenMai;
	}

	public void setKhuyenMai(int khuyenMai) {
		this.khuyenMai = khuyenMai;
	}

	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	public int getThanhTien() {
		return this.thanhTien;
	}

	public void setThanhTien(int thanhTien) {
		this.thanhTien = thanhTien;
	}

	public String getThongTinGiaoHang() {
		return this.thongTinGiaoHang;
	}

	public void setThongTinGiaoHang(String thongTinGiaoHang) {
		this.thongTinGiaoHang = thongTinGiaoHang;
	}

	public Date getNgayLapHoaDon() {
		return this.ngayLapHoaDon;
	}

	public void setNgayLapHoaDon(Date ngayLapHoaDon) {
		this.ngayLapHoaDon = ngayLapHoaDon;
	}

	public Set<LichSuBanHang> getLichSuBanHangs() {
		return this.lichSuBanHangs;
	}

	public void setLichSuBanHangs(Set<LichSuBanHang> lichSuBanHangs) {
		this.lichSuBanHangs = lichSuBanHangs;
	}

}
