package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

/**
 * KhachHang generated by hbm2java
 */
public class KhachHang implements java.io.Serializable {

	private Integer id;
	private KhuVuc khuVuc;
	private String maKhachHang;
	private String tenKhachHang;
	private String diaChi;
	private String maSoThue;
	private String fax;
	private String dienThoai;
	private String diDong;
	private String email;
	private String website;
	private String soTaiKhoan;
	private String nganHang;
	private double gioiHanNo;
	private double noHienTai;
	private float chietKhau;
	private String nguoiLienHe;
	private String nickYahoo;
	private String nickSkype;
	private byte laDaiLy;
	private byte conQuanLy;

	public KhachHang() {
	}

	public KhachHang(KhuVuc khuVuc, String maKhachHang, String tenKhachHang,
			String maSoThue, String fax, String dienThoai, String diDong,
			String soTaiKhoan, String nganHang, double gioiHanNo,
			double noHienTai, float chietKhau, byte laDaiLy, byte conQuanLy) {
		this.khuVuc = khuVuc;
		this.maKhachHang = maKhachHang;
		this.tenKhachHang = tenKhachHang;
		this.maSoThue = maSoThue;
		this.fax = fax;
		this.dienThoai = dienThoai;
		this.diDong = diDong;
		this.soTaiKhoan = soTaiKhoan;
		this.nganHang = nganHang;
		this.gioiHanNo = gioiHanNo;
		this.noHienTai = noHienTai;
		this.chietKhau = chietKhau;
		this.laDaiLy = laDaiLy;
		this.conQuanLy = conQuanLy;
	}

	public KhachHang(KhuVuc khuVuc, String maKhachHang, String tenKhachHang,
			String diaChi, String maSoThue, String fax, String dienThoai,
			String diDong, String email, String website, String soTaiKhoan,
			String nganHang, double gioiHanNo, double noHienTai,
			float chietKhau, String nguoiLienHe, String nickYahoo,
			String nickSkype, byte laDaiLy, byte conQuanLy) {
		this.khuVuc = khuVuc;
		this.maKhachHang = maKhachHang;
		this.tenKhachHang = tenKhachHang;
		this.diaChi = diaChi;
		this.maSoThue = maSoThue;
		this.fax = fax;
		this.dienThoai = dienThoai;
		this.diDong = diDong;
		this.email = email;
		this.website = website;
		this.soTaiKhoan = soTaiKhoan;
		this.nganHang = nganHang;
		this.gioiHanNo = gioiHanNo;
		this.noHienTai = noHienTai;
		this.chietKhau = chietKhau;
		this.nguoiLienHe = nguoiLienHe;
		this.nickYahoo = nickYahoo;
		this.nickSkype = nickSkype;
		this.laDaiLy = laDaiLy;
		this.conQuanLy = conQuanLy;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public KhuVuc getKhuVuc() {
		return this.khuVuc;
	}

	public void setKhuVuc(KhuVuc khuVuc) {
		this.khuVuc = khuVuc;
	}

	public String getMaKhachHang() {
		return this.maKhachHang;
	}

	public void setMaKhachHang(String maKhachHang) {
		this.maKhachHang = maKhachHang;
	}

	public String getTenKhachHang() {
		return this.tenKhachHang;
	}

	public void setTenKhachHang(String tenKhachHang) {
		this.tenKhachHang = tenKhachHang;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getMaSoThue() {
		return this.maSoThue;
	}

	public void setMaSoThue(String maSoThue) {
		this.maSoThue = maSoThue;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	public String getDiDong() {
		return this.diDong;
	}

	public void setDiDong(String diDong) {
		this.diDong = diDong;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getSoTaiKhoan() {
		return this.soTaiKhoan;
	}

	public void setSoTaiKhoan(String soTaiKhoan) {
		this.soTaiKhoan = soTaiKhoan;
	}

	public String getNganHang() {
		return this.nganHang;
	}

	public void setNganHang(String nganHang) {
		this.nganHang = nganHang;
	}

	public double getGioiHanNo() {
		return this.gioiHanNo;
	}

	public void setGioiHanNo(double gioiHanNo) {
		this.gioiHanNo = gioiHanNo;
	}

	public double getNoHienTai() {
		return this.noHienTai;
	}

	public void setNoHienTai(double noHienTai) {
		this.noHienTai = noHienTai;
	}

	public float getChietKhau() {
		return this.chietKhau;
	}

	public void setChietKhau(float chietKhau) {
		this.chietKhau = chietKhau;
	}

	public String getNguoiLienHe() {
		return this.nguoiLienHe;
	}

	public void setNguoiLienHe(String nguoiLienHe) {
		this.nguoiLienHe = nguoiLienHe;
	}

	public String getNickYahoo() {
		return this.nickYahoo;
	}

	public void setNickYahoo(String nickYahoo) {
		this.nickYahoo = nickYahoo;
	}

	public String getNickSkype() {
		return this.nickSkype;
	}

	public void setNickSkype(String nickSkype) {
		this.nickSkype = nickSkype;
	}

	public byte getLaDaiLy() {
		return this.laDaiLy;
	}

	public void setLaDaiLy(byte laDaiLy) {
		this.laDaiLy = laDaiLy;
	}

	public byte getConQuanLy() {
		return this.conQuanLy;
	}

	public void setConQuanLy(byte conQuanLy) {
		this.conQuanLy = conQuanLy;
	}

}
