package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 17, 2016 12:29:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KhachHang generated by hbm2java
 */
public class KhachHang implements java.io.Serializable {

	private Integer id;
	private KhuVuc khuVuc;
	private String tenKhachHang;
	private Date ngaySinh;
	private String diaChi;
	private String dienThoai;
	private String cmnd;
	private int gioiTinh;
	private Date ngayBatDau;
	private Date ngayGiaoDichGanNhat;
	private String thongTinLienQuan;
	private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

	public KhachHang() {
	}

	public KhachHang(KhuVuc khuVuc, String tenKhachHang, Date ngaySinh,
			String diaChi, String dienThoai, String cmnd, int gioiTinh,
			Date ngayBatDau, Date ngayGiaoDichGanNhat, String thongTinLienQuan) {
		this.khuVuc = khuVuc;
		this.tenKhachHang = tenKhachHang;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.cmnd = cmnd;
		this.gioiTinh = gioiTinh;
		this.ngayBatDau = ngayBatDau;
		this.ngayGiaoDichGanNhat = ngayGiaoDichGanNhat;
		this.thongTinLienQuan = thongTinLienQuan;
	}

	public KhachHang(KhuVuc khuVuc, String tenKhachHang, Date ngaySinh,
			String diaChi, String dienThoai, String cmnd, int gioiTinh,
			Date ngayBatDau, Date ngayGiaoDichGanNhat, String thongTinLienQuan,
			Set<HoaDon> hoaDons) {
		this.khuVuc = khuVuc;
		this.tenKhachHang = tenKhachHang;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.cmnd = cmnd;
		this.gioiTinh = gioiTinh;
		this.ngayBatDau = ngayBatDau;
		this.ngayGiaoDichGanNhat = ngayGiaoDichGanNhat;
		this.thongTinLienQuan = thongTinLienQuan;
		this.hoaDons = hoaDons;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public KhuVuc getKhuVuc() {
		return this.khuVuc;
	}

	public void setKhuVuc(KhuVuc khuVuc) {
		this.khuVuc = khuVuc;
	}

	public String getTenKhachHang() {
		return this.tenKhachHang;
	}

	public void setTenKhachHang(String tenKhachHang) {
		this.tenKhachHang = tenKhachHang;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	public int getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(int gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	public Date getNgayBatDau() {
		return this.ngayBatDau;
	}

	public void setNgayBatDau(Date ngayBatDau) {
		this.ngayBatDau = ngayBatDau;
	}

	public Date getNgayGiaoDichGanNhat() {
		return this.ngayGiaoDichGanNhat;
	}

	public void setNgayGiaoDichGanNhat(Date ngayGiaoDichGanNhat) {
		this.ngayGiaoDichGanNhat = ngayGiaoDichGanNhat;
	}

	public String getThongTinLienQuan() {
		return this.thongTinLienQuan;
	}

	public void setThongTinLienQuan(String thongTinLienQuan) {
		this.thongTinLienQuan = thongTinLienQuan;
	}

	public Set<HoaDon> getHoaDons() {
		return this.hoaDons;
	}

	public void setHoaDons(Set<HoaDon> hoaDons) {
		this.hoaDons = hoaDons;
	}

}
