package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 19, 2016 10:56:54 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Kho generated by hbm2java
 */
public class Kho implements java.io.Serializable {

	private Integer id;
	private NhanVien nhanVien;
	private String tenKho;
	private String thongTinKho;
	private Set<HangHoa> hangHoas = new HashSet<HangHoa>(0);

	public Kho() {
	}

	public Kho(NhanVien nhanVien, String tenKho, String thongTinKho) {
		this.nhanVien = nhanVien;
		this.tenKho = tenKho;
		this.thongTinKho = thongTinKho;
	}

	public Kho(NhanVien nhanVien, String tenKho, String thongTinKho,
			Set<HangHoa> hangHoas) {
		this.nhanVien = nhanVien;
		this.tenKho = tenKho;
		this.thongTinKho = thongTinKho;
		this.hangHoas = hangHoas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public NhanVien getNhanVien() {
		return this.nhanVien;
	}

	public void setNhanVien(NhanVien nhanVien) {
		this.nhanVien = nhanVien;
	}

	public String getTenKho() {
		return this.tenKho;
	}

	public void setTenKho(String tenKho) {
		this.tenKho = tenKho;
	}

	public String getThongTinKho() {
		return this.thongTinKho;
	}

	public void setThongTinKho(String thongTinKho) {
		this.thongTinKho = thongTinKho;
	}

	public Set<HangHoa> getHangHoas() {
		return this.hangHoas;
	}

	public void setHangHoas(Set<HangHoa> hangHoas) {
		this.hangHoas = hangHoas;
	}

}
