package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * KhuVuc generated by hbm2java
 */
public class KhuVuc implements java.io.Serializable {

	private Integer id;
	private String maKhuVuc;
	private String tenKhuVuc;
	private String ghiChu;
	private byte conQuanLy;
	private Set<KhachHang> khachHangs = new HashSet<KhachHang>(0);
	private Set<NhaPhanPhoi> nhaPhanPhois = new HashSet<NhaPhanPhoi>(0);

	public KhuVuc() {
	}

	public KhuVuc(String maKhuVuc, String tenKhuVuc, byte conQuanLy) {
		this.maKhuVuc = maKhuVuc;
		this.tenKhuVuc = tenKhuVuc;
		this.conQuanLy = conQuanLy;
	}

	public KhuVuc(String maKhuVuc, String tenKhuVuc, String ghiChu,
			byte conQuanLy, Set<KhachHang> khachHangs,
			Set<NhaPhanPhoi> nhaPhanPhois) {
		this.maKhuVuc = maKhuVuc;
		this.tenKhuVuc = tenKhuVuc;
		this.ghiChu = ghiChu;
		this.conQuanLy = conQuanLy;
		this.khachHangs = khachHangs;
		this.nhaPhanPhois = nhaPhanPhois;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMaKhuVuc() {
		return this.maKhuVuc;
	}

	public void setMaKhuVuc(String maKhuVuc) {
		this.maKhuVuc = maKhuVuc;
	}

	public String getTenKhuVuc() {
		return this.tenKhuVuc;
	}

	public void setTenKhuVuc(String tenKhuVuc) {
		this.tenKhuVuc = tenKhuVuc;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public byte getConQuanLy() {
		return this.conQuanLy;
	}

	public void setConQuanLy(byte conQuanLy) {
		this.conQuanLy = conQuanLy;
	}

	public Set<KhachHang> getKhachHangs() {
		return this.khachHangs;
	}

	public void setKhachHangs(Set<KhachHang> khachHangs) {
		this.khachHangs = khachHangs;
	}

	public Set<NhaPhanPhoi> getNhaPhanPhois() {
		return this.nhaPhanPhois;
	}

	public void setNhaPhanPhois(Set<NhaPhanPhoi> nhaPhanPhois) {
		this.nhaPhanPhois = nhaPhanPhois;
	}

}
