package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 19, 2016 10:56:54 PM by Hibernate Tools 4.0.0

/**
 * LichSuBanHang generated by hbm2java
 */
public class LichSuBanHang implements java.io.Serializable {

	private Integer id;
	private HoaDon hoaDon;
	private HangHoa hangHoa;
	private String thaoTac;

	public LichSuBanHang() {
	}

	public LichSuBanHang(HoaDon hoaDon, HangHoa hangHoa, String thaoTac) {
		this.hoaDon = hoaDon;
		this.hangHoa = hangHoa;
		this.thaoTac = thaoTac;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public HoaDon getHoaDon() {
		return this.hoaDon;
	}

	public void setHoaDon(HoaDon hoaDon) {
		this.hoaDon = hoaDon;
	}

	public HangHoa getHangHoa() {
		return this.hangHoa;
	}

	public void setHangHoa(HangHoa hangHoa) {
		this.hangHoa = hangHoa;
	}

	public String getThaoTac() {
		return this.thaoTac;
	}

	public void setThaoTac(String thaoTac) {
		this.thaoTac = thaoTac;
	}

}
