package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 19, 2016 10:56:54 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * LoaiHangHoa generated by hbm2java
 */
public class LoaiHangHoa implements java.io.Serializable {

	private Integer id;
	private String tenLoaiHang;
	private String donViTinh;
	private Set<HangHoa> hangHoas = new HashSet<HangHoa>(0);

	public LoaiHangHoa() {
	}

	public LoaiHangHoa(String tenLoaiHang, String donViTinh) {
		this.tenLoaiHang = tenLoaiHang;
		this.donViTinh = donViTinh;
	}

	public LoaiHangHoa(String tenLoaiHang, String donViTinh,
			Set<HangHoa> hangHoas) {
		this.tenLoaiHang = tenLoaiHang;
		this.donViTinh = donViTinh;
		this.hangHoas = hangHoas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTenLoaiHang() {
		return this.tenLoaiHang;
	}

	public void setTenLoaiHang(String tenLoaiHang) {
		this.tenLoaiHang = tenLoaiHang;
	}

	public String getDonViTinh() {
		return this.donViTinh;
	}

	public void setDonViTinh(String donViTinh) {
		this.donViTinh = donViTinh;
	}

	public Set<HangHoa> getHangHoas() {
		return this.hangHoas;
	}

	public void setHangHoas(Set<HangHoa> hangHoas) {
		this.hangHoas = hangHoas;
	}

}
