package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MuaHang generated by hbm2java
 */
public class MuaHang implements java.io.Serializable {

	private Integer id;
	private int idNhaPhanPhoi;
	private String ghiChu;
	private String dieuKhoanThanhToan;
	private Date ngayThanhToan;
	private long tongSoLuong;
	private double tongThanhTien;
	private double tongThanhToan;
	private Date ngayNhap;
	private Set<ChiTietMuaHang> chiTietMuaHangs = new HashSet<ChiTietMuaHang>(0);
	private Set<PhieuMuaHang> phieuMuaHangs = new HashSet<PhieuMuaHang>(0);
	private Set<PhieuChi> phieuChis = new HashSet<PhieuChi>(0);

	public MuaHang() {
	}

	public MuaHang(int idNhaPhanPhoi, Date ngayThanhToan, long tongSoLuong,
			double tongThanhTien, double tongThanhToan, Date ngayNhap) {
		this.idNhaPhanPhoi = idNhaPhanPhoi;
		this.ngayThanhToan = ngayThanhToan;
		this.tongSoLuong = tongSoLuong;
		this.tongThanhTien = tongThanhTien;
		this.tongThanhToan = tongThanhToan;
		this.ngayNhap = ngayNhap;
	}

	public MuaHang(int idNhaPhanPhoi, String ghiChu, String dieuKhoanThanhToan,
			Date ngayThanhToan, long tongSoLuong, double tongThanhTien,
			double tongThanhToan, Date ngayNhap,
			Set<ChiTietMuaHang> chiTietMuaHangs,
			Set<PhieuMuaHang> phieuMuaHangs, Set<PhieuChi> phieuChis) {
		this.idNhaPhanPhoi = idNhaPhanPhoi;
		this.ghiChu = ghiChu;
		this.dieuKhoanThanhToan = dieuKhoanThanhToan;
		this.ngayThanhToan = ngayThanhToan;
		this.tongSoLuong = tongSoLuong;
		this.tongThanhTien = tongThanhTien;
		this.tongThanhToan = tongThanhToan;
		this.ngayNhap = ngayNhap;
		this.chiTietMuaHangs = chiTietMuaHangs;
		this.phieuMuaHangs = phieuMuaHangs;
		this.phieuChis = phieuChis;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdNhaPhanPhoi() {
		return this.idNhaPhanPhoi;
	}

	public void setIdNhaPhanPhoi(int idNhaPhanPhoi) {
		this.idNhaPhanPhoi = idNhaPhanPhoi;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public String getDieuKhoanThanhToan() {
		return this.dieuKhoanThanhToan;
	}

	public void setDieuKhoanThanhToan(String dieuKhoanThanhToan) {
		this.dieuKhoanThanhToan = dieuKhoanThanhToan;
	}

	public Date getNgayThanhToan() {
		return this.ngayThanhToan;
	}

	public void setNgayThanhToan(Date ngayThanhToan) {
		this.ngayThanhToan = ngayThanhToan;
	}

	public long getTongSoLuong() {
		return this.tongSoLuong;
	}

	public void setTongSoLuong(long tongSoLuong) {
		this.tongSoLuong = tongSoLuong;
	}

	public double getTongThanhTien() {
		return this.tongThanhTien;
	}

	public void setTongThanhTien(double tongThanhTien) {
		this.tongThanhTien = tongThanhTien;
	}

	public double getTongThanhToan() {
		return this.tongThanhToan;
	}

	public void setTongThanhToan(double tongThanhToan) {
		this.tongThanhToan = tongThanhToan;
	}

	public Date getNgayNhap() {
		return this.ngayNhap;
	}

	public void setNgayNhap(Date ngayNhap) {
		this.ngayNhap = ngayNhap;
	}

	public Set<ChiTietMuaHang> getChiTietMuaHangs() {
		return this.chiTietMuaHangs;
	}

	public void setChiTietMuaHangs(Set<ChiTietMuaHang> chiTietMuaHangs) {
		this.chiTietMuaHangs = chiTietMuaHangs;
	}

	public Set<PhieuMuaHang> getPhieuMuaHangs() {
		return this.phieuMuaHangs;
	}

	public void setPhieuMuaHangs(Set<PhieuMuaHang> phieuMuaHangs) {
		this.phieuMuaHangs = phieuMuaHangs;
	}

	public Set<PhieuChi> getPhieuChis() {
		return this.phieuChis;
	}

	public void setPhieuChis(Set<PhieuChi> phieuChis) {
		this.phieuChis = phieuChis;
	}

}
