package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 19, 2016 10:56:54 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NhanVien generated by hbm2java
 */
public class NhanVien implements java.io.Serializable {

	private Integer id;
	private BoPhan boPhan;
	private String tenDayDu;
	private Date ngaySinh;
	private String diaChi;
	private String dienThoai;
	private String email;
	private int gioiTinh;
	private Date ngayBatDau;
	private int loaiNhanVien;
	private Set<KhuVuc> khuVucs = new HashSet<KhuVuc>(0);
	private Set<KhuVuc> khuVucs_1 = new HashSet<KhuVuc>(0);
	private Set<Kho> khos = new HashSet<Kho>(0);
	private Set<NguoiDung> nguoiDungs = new HashSet<NguoiDung>(0);

	public NhanVien() {
	}

	public NhanVien(BoPhan boPhan, String tenDayDu, Date ngaySinh,
			String diaChi, String dienThoai, String email, int gioiTinh,
			Date ngayBatDau, int loaiNhanVien) {
		this.boPhan = boPhan;
		this.tenDayDu = tenDayDu;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.email = email;
		this.gioiTinh = gioiTinh;
		this.ngayBatDau = ngayBatDau;
		this.loaiNhanVien = loaiNhanVien;
	}

	public NhanVien(BoPhan boPhan, String tenDayDu, Date ngaySinh,
			String diaChi, String dienThoai, String email, int gioiTinh,
			Date ngayBatDau, int loaiNhanVien, Set<KhuVuc> khuVucs,
			Set<KhuVuc> khuVucs_1, Set<Kho> khos, Set<NguoiDung> nguoiDungs) {
		this.boPhan = boPhan;
		this.tenDayDu = tenDayDu;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.email = email;
		this.gioiTinh = gioiTinh;
		this.ngayBatDau = ngayBatDau;
		this.loaiNhanVien = loaiNhanVien;
		this.khuVucs = khuVucs;
		this.khuVucs_1 = khuVucs_1;
		this.khos = khos;
		this.nguoiDungs = nguoiDungs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BoPhan getBoPhan() {
		return this.boPhan;
	}

	public void setBoPhan(BoPhan boPhan) {
		this.boPhan = boPhan;
	}

	public String getTenDayDu() {
		return this.tenDayDu;
	}

	public void setTenDayDu(String tenDayDu) {
		this.tenDayDu = tenDayDu;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(int gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	public Date getNgayBatDau() {
		return this.ngayBatDau;
	}

	public void setNgayBatDau(Date ngayBatDau) {
		this.ngayBatDau = ngayBatDau;
	}

	public int getLoaiNhanVien() {
		return this.loaiNhanVien;
	}

	public void setLoaiNhanVien(int loaiNhanVien) {
		this.loaiNhanVien = loaiNhanVien;
	}

	public Set<KhuVuc> getKhuVucs() {
		return this.khuVucs;
	}

	public void setKhuVucs(Set<KhuVuc> khuVucs) {
		this.khuVucs = khuVucs;
	}

	public Set<KhuVuc> getKhuVucs_1() {
		return this.khuVucs_1;
	}

	public void setKhuVucs_1(Set<KhuVuc> khuVucs_1) {
		this.khuVucs_1 = khuVucs_1;
	}

	public Set<Kho> getKhos() {
		return this.khos;
	}

	public void setKhos(Set<Kho> khos) {
		this.khos = khos;
	}

	public Set<NguoiDung> getNguoiDungs() {
		return this.nguoiDungs;
	}

	public void setNguoiDungs(Set<NguoiDung> nguoiDungs) {
		this.nguoiDungs = nguoiDungs;
	}

}
