package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 19, 2016 10:56:54 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NhaPhanPhoi generated by hbm2java
 */
public class NhaPhanPhoi implements java.io.Serializable {

	private Integer id;
	private KhuVuc khuVuc;
	private String tenNhaPhanPhoi;
	private Date ngayKyHopDong;
	private String diaChi;
	private String dienThoai;
	private String email;
	private String nguoiDaiDien;
	private Date ngayGiaoDichGanNhat;
	private int chietKhau;
	private String thongTinLienQuan;
	private Set<HangHoa> hangHoas = new HashSet<HangHoa>(0);

	public NhaPhanPhoi() {
	}

	public NhaPhanPhoi(KhuVuc khuVuc, String tenNhaPhanPhoi,
			Date ngayKyHopDong, String diaChi, String dienThoai, String email,
			String nguoiDaiDien, Date ngayGiaoDichGanNhat, int chietKhau,
			String thongTinLienQuan) {
		this.khuVuc = khuVuc;
		this.tenNhaPhanPhoi = tenNhaPhanPhoi;
		this.ngayKyHopDong = ngayKyHopDong;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.email = email;
		this.nguoiDaiDien = nguoiDaiDien;
		this.ngayGiaoDichGanNhat = ngayGiaoDichGanNhat;
		this.chietKhau = chietKhau;
		this.thongTinLienQuan = thongTinLienQuan;
	}

	public NhaPhanPhoi(KhuVuc khuVuc, String tenNhaPhanPhoi,
			Date ngayKyHopDong, String diaChi, String dienThoai, String email,
			String nguoiDaiDien, Date ngayGiaoDichGanNhat, int chietKhau,
			String thongTinLienQuan, Set<HangHoa> hangHoas) {
		this.khuVuc = khuVuc;
		this.tenNhaPhanPhoi = tenNhaPhanPhoi;
		this.ngayKyHopDong = ngayKyHopDong;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.email = email;
		this.nguoiDaiDien = nguoiDaiDien;
		this.ngayGiaoDichGanNhat = ngayGiaoDichGanNhat;
		this.chietKhau = chietKhau;
		this.thongTinLienQuan = thongTinLienQuan;
		this.hangHoas = hangHoas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public KhuVuc getKhuVuc() {
		return this.khuVuc;
	}

	public void setKhuVuc(KhuVuc khuVuc) {
		this.khuVuc = khuVuc;
	}

	public String getTenNhaPhanPhoi() {
		return this.tenNhaPhanPhoi;
	}

	public void setTenNhaPhanPhoi(String tenNhaPhanPhoi) {
		this.tenNhaPhanPhoi = tenNhaPhanPhoi;
	}

	public Date getNgayKyHopDong() {
		return this.ngayKyHopDong;
	}

	public void setNgayKyHopDong(Date ngayKyHopDong) {
		this.ngayKyHopDong = ngayKyHopDong;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNguoiDaiDien() {
		return this.nguoiDaiDien;
	}

	public void setNguoiDaiDien(String nguoiDaiDien) {
		this.nguoiDaiDien = nguoiDaiDien;
	}

	public Date getNgayGiaoDichGanNhat() {
		return this.ngayGiaoDichGanNhat;
	}

	public void setNgayGiaoDichGanNhat(Date ngayGiaoDichGanNhat) {
		this.ngayGiaoDichGanNhat = ngayGiaoDichGanNhat;
	}

	public int getChietKhau() {
		return this.chietKhau;
	}

	public void setChietKhau(int chietKhau) {
		this.chietKhau = chietKhau;
	}

	public String getThongTinLienQuan() {
		return this.thongTinLienQuan;
	}

	public void setThongTinLienQuan(String thongTinLienQuan) {
		this.thongTinLienQuan = thongTinLienQuan;
	}

	public Set<HangHoa> getHangHoas() {
		return this.hangHoas;
	}

	public void setHangHoas(Set<HangHoa> hangHoas) {
		this.hangHoas = hangHoas;
	}

}
