package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * NhaPhanPhoi generated by hbm2java
 */
public class NhaPhanPhoi implements java.io.Serializable {

	private Integer id;
	private KhuVuc khuVuc;
	private String maNhaPhanPhoi;
	private String tenNhaPhanPhoi;
	private String diaChi;
	private String maSoThue;
	private String fax;
	private String dienThoai;
	private String diDong;
	private String email;
	private String website;
	private String soTaiKhoan;
	private String nganHang;
	private double gioiHanNo;
	private double noHienTai;
	private float chietKhau;
	private String nguoiLienHe;
	private String chucVu;
	private byte conQuanLy;
	private Set<HangHoa> hangHoas = new HashSet<HangHoa>(0);

	public NhaPhanPhoi() {
	}

	public NhaPhanPhoi(KhuVuc khuVuc, String maNhaPhanPhoi,
			String tenNhaPhanPhoi, String maSoThue, double gioiHanNo,
			double noHienTai, float chietKhau, byte conQuanLy) {
		this.khuVuc = khuVuc;
		this.maNhaPhanPhoi = maNhaPhanPhoi;
		this.tenNhaPhanPhoi = tenNhaPhanPhoi;
		this.maSoThue = maSoThue;
		this.gioiHanNo = gioiHanNo;
		this.noHienTai = noHienTai;
		this.chietKhau = chietKhau;
		this.conQuanLy = conQuanLy;
	}

	public NhaPhanPhoi(KhuVuc khuVuc, String maNhaPhanPhoi,
			String tenNhaPhanPhoi, String diaChi, String maSoThue, String fax,
			String dienThoai, String diDong, String email, String website,
			String soTaiKhoan, String nganHang, double gioiHanNo,
			double noHienTai, float chietKhau, String nguoiLienHe,
			String chucVu, byte conQuanLy, Set<HangHoa> hangHoas) {
		this.khuVuc = khuVuc;
		this.maNhaPhanPhoi = maNhaPhanPhoi;
		this.tenNhaPhanPhoi = tenNhaPhanPhoi;
		this.diaChi = diaChi;
		this.maSoThue = maSoThue;
		this.fax = fax;
		this.dienThoai = dienThoai;
		this.diDong = diDong;
		this.email = email;
		this.website = website;
		this.soTaiKhoan = soTaiKhoan;
		this.nganHang = nganHang;
		this.gioiHanNo = gioiHanNo;
		this.noHienTai = noHienTai;
		this.chietKhau = chietKhau;
		this.nguoiLienHe = nguoiLienHe;
		this.chucVu = chucVu;
		this.conQuanLy = conQuanLy;
		this.hangHoas = hangHoas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public KhuVuc getKhuVuc() {
		return this.khuVuc;
	}

	public void setKhuVuc(KhuVuc khuVuc) {
		this.khuVuc = khuVuc;
	}

	public String getMaNhaPhanPhoi() {
		return this.maNhaPhanPhoi;
	}

	public void setMaNhaPhanPhoi(String maNhaPhanPhoi) {
		this.maNhaPhanPhoi = maNhaPhanPhoi;
	}

	public String getTenNhaPhanPhoi() {
		return this.tenNhaPhanPhoi;
	}

	public void setTenNhaPhanPhoi(String tenNhaPhanPhoi) {
		this.tenNhaPhanPhoi = tenNhaPhanPhoi;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getMaSoThue() {
		return this.maSoThue;
	}

	public void setMaSoThue(String maSoThue) {
		this.maSoThue = maSoThue;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	public String getDiDong() {
		return this.diDong;
	}

	public void setDiDong(String diDong) {
		this.diDong = diDong;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getSoTaiKhoan() {
		return this.soTaiKhoan;
	}

	public void setSoTaiKhoan(String soTaiKhoan) {
		this.soTaiKhoan = soTaiKhoan;
	}

	public String getNganHang() {
		return this.nganHang;
	}

	public void setNganHang(String nganHang) {
		this.nganHang = nganHang;
	}

	public double getGioiHanNo() {
		return this.gioiHanNo;
	}

	public void setGioiHanNo(double gioiHanNo) {
		this.gioiHanNo = gioiHanNo;
	}

	public double getNoHienTai() {
		return this.noHienTai;
	}

	public void setNoHienTai(double noHienTai) {
		this.noHienTai = noHienTai;
	}

	public float getChietKhau() {
		return this.chietKhau;
	}

	public void setChietKhau(float chietKhau) {
		this.chietKhau = chietKhau;
	}

	public String getNguoiLienHe() {
		return this.nguoiLienHe;
	}

	public void setNguoiLienHe(String nguoiLienHe) {
		this.nguoiLienHe = nguoiLienHe;
	}

	public String getChucVu() {
		return this.chucVu;
	}

	public void setChucVu(String chucVu) {
		this.chucVu = chucVu;
	}

	public byte getConQuanLy() {
		return this.conQuanLy;
	}

	public void setConQuanLy(byte conQuanLy) {
		this.conQuanLy = conQuanLy;
	}

	public Set<HangHoa> getHangHoas() {
		return this.hangHoas;
	}

	public void setHangHoas(Set<HangHoa> hangHoas) {
		this.hangHoas = hangHoas;
	}

}
