package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * NhatKyHeThong generated by hbm2java
 */
public class NhatKyHeThong implements java.io.Serializable {

	private Integer id;
	private int idNguoiDung;
	private String thaoTac;
	private String chiTiet;
	private String ghiChu;
	private Date ngay;

	public NhatKyHeThong() {
	}

	public NhatKyHeThong(int idNguoiDung, Date ngay) {
		this.idNguoiDung = idNguoiDung;
		this.ngay = ngay;
	}

	public NhatKyHeThong(int idNguoiDung, String thaoTac, String chiTiet,
			String ghiChu, Date ngay) {
		this.idNguoiDung = idNguoiDung;
		this.thaoTac = thaoTac;
		this.chiTiet = chiTiet;
		this.ghiChu = ghiChu;
		this.ngay = ngay;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdNguoiDung() {
		return this.idNguoiDung;
	}

	public void setIdNguoiDung(int idNguoiDung) {
		this.idNguoiDung = idNguoiDung;
	}

	public String getThaoTac() {
		return this.thaoTac;
	}

	public void setThaoTac(String thaoTac) {
		this.thaoTac = thaoTac;
	}

	public String getChiTiet() {
		return this.chiTiet;
	}

	public void setChiTiet(String chiTiet) {
		this.chiTiet = chiTiet;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

}
