package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 11:10:20 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * NhomNguoiDung generated by hbm2java
 */
public class NhomNguoiDung implements java.io.Serializable {

	private Integer id;
	private String tenNhom;
	private String moTa;
	private int conQuanLy;
	private Set<NguoiDung> nguoiDungs = new HashSet<NguoiDung>(0);
	private Set<PhanQuyen> phanQuyens = new HashSet<PhanQuyen>(0);

	public NhomNguoiDung() {
	}

	public NhomNguoiDung(String tenNhom, int conQuanLy) {
		this.tenNhom = tenNhom;
		this.conQuanLy = conQuanLy;
	}

	public NhomNguoiDung(String tenNhom, String moTa, int conQuanLy,
			Set<NguoiDung> nguoiDungs, Set<PhanQuyen> phanQuyens) {
		this.tenNhom = tenNhom;
		this.moTa = moTa;
		this.conQuanLy = conQuanLy;
		this.nguoiDungs = nguoiDungs;
		this.phanQuyens = phanQuyens;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTenNhom() {
		return this.tenNhom;
	}

	public void setTenNhom(String tenNhom) {
		this.tenNhom = tenNhom;
	}

	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	public int getConQuanLy() {
		return this.conQuanLy;
	}

	public void setConQuanLy(int conQuanLy) {
		this.conQuanLy = conQuanLy;
	}

	public Set<NguoiDung> getNguoiDungs() {
		return this.nguoiDungs;
	}

	public void setNguoiDungs(Set<NguoiDung> nguoiDungs) {
		this.nguoiDungs = nguoiDungs;
	}

	public Set<PhanQuyen> getPhanQuyens() {
		return this.phanQuyens;
	}

	public void setPhanQuyens(Set<PhanQuyen> phanQuyens) {
		this.phanQuyens = phanQuyens;
	}

}
