package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

/**
 * PhanQuyen generated by hbm2java
 */
public class PhanQuyen implements java.io.Serializable {

	private Integer id;
	private NhomNguoiDung nhomNguoiDung;
	private byte nhatKyHeThong;
	private byte backup;
	private byte restore;
	private byte phanQuyen;
	private byte khuVuc;
	private byte khachHang;
	private byte nhaPhanPhoi;
	private byte hangHoa;
	private byte donViTinh;
	private byte nhomHang;
	private byte kho;
	private byte boPhan;
	private byte nhanVien;
	private byte muaHang;
	private byte banHang;
	private byte chuyenKho;
	private byte tonKho;
	private byte thuTien;
	private byte traTien;
	private byte nguoiDung;
	private byte lichSuHangHoa;
	private byte report;
	private byte tyGia;

	public PhanQuyen() {
	}

	public PhanQuyen(NhomNguoiDung nhomNguoiDung, byte nhatKyHeThong,
			byte backup, byte restore, byte phanQuyen, byte khuVuc,
			byte khachHang, byte nhaPhanPhoi, byte hangHoa, byte donViTinh,
			byte nhomHang, byte kho, byte boPhan, byte nhanVien, byte muaHang,
			byte banHang, byte chuyenKho, byte tonKho, byte thuTien,
			byte traTien, byte nguoiDung, byte lichSuHangHoa, byte report,
			byte tyGia) {
		this.nhomNguoiDung = nhomNguoiDung;
		this.nhatKyHeThong = nhatKyHeThong;
		this.backup = backup;
		this.restore = restore;
		this.phanQuyen = phanQuyen;
		this.khuVuc = khuVuc;
		this.khachHang = khachHang;
		this.nhaPhanPhoi = nhaPhanPhoi;
		this.hangHoa = hangHoa;
		this.donViTinh = donViTinh;
		this.nhomHang = nhomHang;
		this.kho = kho;
		this.boPhan = boPhan;
		this.nhanVien = nhanVien;
		this.muaHang = muaHang;
		this.banHang = banHang;
		this.chuyenKho = chuyenKho;
		this.tonKho = tonKho;
		this.thuTien = thuTien;
		this.traTien = traTien;
		this.nguoiDung = nguoiDung;
		this.lichSuHangHoa = lichSuHangHoa;
		this.report = report;
		this.tyGia = tyGia;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public NhomNguoiDung getNhomNguoiDung() {
		return this.nhomNguoiDung;
	}

	public void setNhomNguoiDung(NhomNguoiDung nhomNguoiDung) {
		this.nhomNguoiDung = nhomNguoiDung;
	}

	public byte getNhatKyHeThong() {
		return this.nhatKyHeThong;
	}

	public void setNhatKyHeThong(byte nhatKyHeThong) {
		this.nhatKyHeThong = nhatKyHeThong;
	}

	public byte getBackup() {
		return this.backup;
	}

	public void setBackup(byte backup) {
		this.backup = backup;
	}

	public byte getRestore() {
		return this.restore;
	}

	public void setRestore(byte restore) {
		this.restore = restore;
	}

	public byte getPhanQuyen() {
		return this.phanQuyen;
	}

	public void setPhanQuyen(byte phanQuyen) {
		this.phanQuyen = phanQuyen;
	}

	public byte getKhuVuc() {
		return this.khuVuc;
	}

	public void setKhuVuc(byte khuVuc) {
		this.khuVuc = khuVuc;
	}

	public byte getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(byte khachHang) {
		this.khachHang = khachHang;
	}

	public byte getNhaPhanPhoi() {
		return this.nhaPhanPhoi;
	}

	public void setNhaPhanPhoi(byte nhaPhanPhoi) {
		this.nhaPhanPhoi = nhaPhanPhoi;
	}

	public byte getHangHoa() {
		return this.hangHoa;
	}

	public void setHangHoa(byte hangHoa) {
		this.hangHoa = hangHoa;
	}

	public byte getDonViTinh() {
		return this.donViTinh;
	}

	public void setDonViTinh(byte donViTinh) {
		this.donViTinh = donViTinh;
	}

	public byte getNhomHang() {
		return this.nhomHang;
	}

	public void setNhomHang(byte nhomHang) {
		this.nhomHang = nhomHang;
	}

	public byte getKho() {
		return this.kho;
	}

	public void setKho(byte kho) {
		this.kho = kho;
	}

	public byte getBoPhan() {
		return this.boPhan;
	}

	public void setBoPhan(byte boPhan) {
		this.boPhan = boPhan;
	}

	public byte getNhanVien() {
		return this.nhanVien;
	}

	public void setNhanVien(byte nhanVien) {
		this.nhanVien = nhanVien;
	}

	public byte getMuaHang() {
		return this.muaHang;
	}

	public void setMuaHang(byte muaHang) {
		this.muaHang = muaHang;
	}

	public byte getBanHang() {
		return this.banHang;
	}

	public void setBanHang(byte banHang) {
		this.banHang = banHang;
	}

	public byte getChuyenKho() {
		return this.chuyenKho;
	}

	public void setChuyenKho(byte chuyenKho) {
		this.chuyenKho = chuyenKho;
	}

	public byte getTonKho() {
		return this.tonKho;
	}

	public void setTonKho(byte tonKho) {
		this.tonKho = tonKho;
	}

	public byte getThuTien() {
		return this.thuTien;
	}

	public void setThuTien(byte thuTien) {
		this.thuTien = thuTien;
	}

	public byte getTraTien() {
		return this.traTien;
	}

	public void setTraTien(byte traTien) {
		this.traTien = traTien;
	}

	public byte getNguoiDung() {
		return this.nguoiDung;
	}

	public void setNguoiDung(byte nguoiDung) {
		this.nguoiDung = nguoiDung;
	}

	public byte getLichSuHangHoa() {
		return this.lichSuHangHoa;
	}

	public void setLichSuHangHoa(byte lichSuHangHoa) {
		this.lichSuHangHoa = lichSuHangHoa;
	}

	public byte getReport() {
		return this.report;
	}

	public void setReport(byte report) {
		this.report = report;
	}

	public byte getTyGia() {
		return this.tyGia;
	}

	public void setTyGia(byte tyGia) {
		this.tyGia = tyGia;
	}

}
