package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PhieuBanHang generated by hbm2java
 */
public class PhieuBanHang implements java.io.Serializable {

	private Integer id;
	private BanHang banHang;
	private String maPhieu;
	private Date ngay;
	private double duNo;
	private String ghiChu;
	private int idNguoiDung;

	public PhieuBanHang() {
	}

	public PhieuBanHang(BanHang banHang, String maPhieu, Date ngay,
			double duNo, int idNguoiDung) {
		this.banHang = banHang;
		this.maPhieu = maPhieu;
		this.ngay = ngay;
		this.duNo = duNo;
		this.idNguoiDung = idNguoiDung;
	}

	public PhieuBanHang(BanHang banHang, String maPhieu, Date ngay,
			double duNo, String ghiChu, int idNguoiDung) {
		this.banHang = banHang;
		this.maPhieu = maPhieu;
		this.ngay = ngay;
		this.duNo = duNo;
		this.ghiChu = ghiChu;
		this.idNguoiDung = idNguoiDung;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BanHang getBanHang() {
		return this.banHang;
	}

	public void setBanHang(BanHang banHang) {
		this.banHang = banHang;
	}

	public String getMaPhieu() {
		return this.maPhieu;
	}

	public void setMaPhieu(String maPhieu) {
		this.maPhieu = maPhieu;
	}

	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	public double getDuNo() {
		return this.duNo;
	}

	public void setDuNo(double duNo) {
		this.duNo = duNo;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public int getIdNguoiDung() {
		return this.idNguoiDung;
	}

	public void setIdNguoiDung(int idNguoiDung) {
		this.idNguoiDung = idNguoiDung;
	}

}
