package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PhieuMuaHang generated by hbm2java
 */
public class PhieuMuaHang implements java.io.Serializable {

	private Integer id;
	private MuaHang muaHang;
	private String maPhieu;
	private double noCu;
	private double noMoi;
	private int loaiTien;
	private String ghiChu;
	private int idNguoiDung;
	private Date ngay;

	public PhieuMuaHang() {
	}

	public PhieuMuaHang(MuaHang muaHang, String maPhieu, double noCu,
			double noMoi, int loaiTien, int idNguoiDung, Date ngay) {
		this.muaHang = muaHang;
		this.maPhieu = maPhieu;
		this.noCu = noCu;
		this.noMoi = noMoi;
		this.loaiTien = loaiTien;
		this.idNguoiDung = idNguoiDung;
		this.ngay = ngay;
	}

	public PhieuMuaHang(MuaHang muaHang, String maPhieu, double noCu,
			double noMoi, int loaiTien, String ghiChu, int idNguoiDung,
			Date ngay) {
		this.muaHang = muaHang;
		this.maPhieu = maPhieu;
		this.noCu = noCu;
		this.noMoi = noMoi;
		this.loaiTien = loaiTien;
		this.ghiChu = ghiChu;
		this.idNguoiDung = idNguoiDung;
		this.ngay = ngay;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MuaHang getMuaHang() {
		return this.muaHang;
	}

	public void setMuaHang(MuaHang muaHang) {
		this.muaHang = muaHang;
	}

	public String getMaPhieu() {
		return this.maPhieu;
	}

	public void setMaPhieu(String maPhieu) {
		this.maPhieu = maPhieu;
	}

	public double getNoCu() {
		return this.noCu;
	}

	public void setNoCu(double noCu) {
		this.noCu = noCu;
	}

	public double getNoMoi() {
		return this.noMoi;
	}

	public void setNoMoi(double noMoi) {
		this.noMoi = noMoi;
	}

	public int getLoaiTien() {
		return this.loaiTien;
	}

	public void setLoaiTien(int loaiTien) {
		this.loaiTien = loaiTien;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public int getIdNguoiDung() {
		return this.idNguoiDung;
	}

	public void setIdNguoiDung(int idNguoiDung) {
		this.idNguoiDung = idNguoiDung;
	}

	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

}
