package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 17, 2016 12:29:30 AM by Hibernate Tools 3.4.0.CR1

/**
 * ThongTinPhanMem generated by hbm2java
 */
public class ThongTinPhanMem implements java.io.Serializable {

	private Integer id;
	private String tenDonVi;
	private String diaChi;
	private String dienThoai;
	private String fax;
	private String website;
	private String email;
	private String linhVuc;
	private String maSoThue;
	private String gpkd;

	public ThongTinPhanMem() {
	}

	public ThongTinPhanMem(String tenDonVi, String diaChi, String dienThoai,
			String fax, String website, String email, String linhVuc,
			String maSoThue, String gpkd) {
		this.tenDonVi = tenDonVi;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.fax = fax;
		this.website = website;
		this.email = email;
		this.linhVuc = linhVuc;
		this.maSoThue = maSoThue;
		this.gpkd = gpkd;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTenDonVi() {
		return this.tenDonVi;
	}

	public void setTenDonVi(String tenDonVi) {
		this.tenDonVi = tenDonVi;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLinhVuc() {
		return this.linhVuc;
	}

	public void setLinhVuc(String linhVuc) {
		this.linhVuc = linhVuc;
	}

	public String getMaSoThue() {
		return this.maSoThue;
	}

	public void setMaSoThue(String maSoThue) {
		this.maSoThue = maSoThue;
	}

	public String getGpkd() {
		return this.gpkd;
	}

	public void setGpkd(String gpkd) {
		this.gpkd = gpkd;
	}

}
