package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

/**
 * ThongTinDonViSuDung generated by hbm2java
 */
public class ThongTinDonViSuDung implements java.io.Serializable {

	private Integer id;
	private String tenCongTy;
	private String diaChi;
	private String dienThoai;
	private String fax;
	private String email;
	private String website;
	private String linhVuc;
	private String maSoThue;
	private String giayPhepKinhDoanh;

	public ThongTinDonViSuDung() {
	}

	public ThongTinDonViSuDung(String tenCongTy, String diaChi,
			String dienThoai, String fax, String email, String website,
			String linhVuc, String maSoThue, String giayPhepKinhDoanh) {
		this.tenCongTy = tenCongTy;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.fax = fax;
		this.email = email;
		this.website = website;
		this.linhVuc = linhVuc;
		this.maSoThue = maSoThue;
		this.giayPhepKinhDoanh = giayPhepKinhDoanh;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTenCongTy() {
		return this.tenCongTy;
	}

	public void setTenCongTy(String tenCongTy) {
		this.tenCongTy = tenCongTy;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getLinhVuc() {
		return this.linhVuc;
	}

	public void setLinhVuc(String linhVuc) {
		this.linhVuc = linhVuc;
	}

	public String getMaSoThue() {
		return this.maSoThue;
	}

	public void setMaSoThue(String maSoThue) {
		this.maSoThue = maSoThue;
	}

	public String getGiayPhepKinhDoanh() {
		return this.giayPhepKinhDoanh;
	}

	public void setGiayPhepKinhDoanh(String giayPhepKinhDoanh) {
		this.giayPhepKinhDoanh = giayPhepKinhDoanh;
	}

}
