package com.nhom28.quanlibanhang.pojo;

// default package
// Generated Oct 20, 2016 9:05:28 PM by Hibernate Tools 4.0.0

/**
 * TyGia generated by hbm2java
 */
public class TyGia implements java.io.Serializable {

	private Integer id;
	private String maLoaiTien;
	private String loaiTien;
	private double tyGiaVnd;

	public TyGia() {
	}

	public TyGia(String maLoaiTien, String loaiTien, double tyGiaVnd) {
		this.maLoaiTien = maLoaiTien;
		this.loaiTien = loaiTien;
		this.tyGiaVnd = tyGiaVnd;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMaLoaiTien() {
		return this.maLoaiTien;
	}

	public void setMaLoaiTien(String maLoaiTien) {
		this.maLoaiTien = maLoaiTien;
	}

	public String getLoaiTien() {
		return this.loaiTien;
	}

	public void setLoaiTien(String loaiTien) {
		this.loaiTien = loaiTien;
	}

	public double getTyGiaVnd() {
		return this.tyGiaVnd;
	}

	public void setTyGiaVnd(double tyGiaVnd) {
		this.tyGiaVnd = tyGiaVnd;
	}

}
